[package]
name = "e_grid"
version = "0.1.0"
edition = "2021"
[patch.crates-io]
iceoryx2-pal-posix = { path = "C:\\w\\iceoryx2-pal-posix-0.6.1" }

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "processthreadsapi", "shellapi", "consoleapi", "errhandlingapi"] }
crossterm = "0.27"
iceoryx2 = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
dashmap = "5.5"
once_cell = "1.19"
ctrlc = "3.0"
ratatui = "0.28"
log = "0.4"
env_logger = "0.11"
bincode = "1.3"

[[bin]]
name = "e_grid"
path = "src/e_grid.rs"

[[bin]]
name = "grid_tracker_legacy"
path = "src/main.rs"

[[bin]]
name = "simple_test"
path = "src/simple_test.rs"

[[bin]]
name = "simple_grid"
path = "src/simple_grid.rs"

[[bin]]
name = "basic_grid"
path = "src/basic_grid.rs"

[[bin]]
name = "monitor_test"
path = "src/monitor_test.rs"

[[bin]]
name = "simple_grid_new"
path = "src/simple_grid_new.rs"

[[bin]]
name = "basic_example"
path = "src/basic_example.rs"

[[bin]]
name = "debug_positions"
path = "src/debug_positions.rs"

[[bin]]
name = "ipc_demo"
path = "src/ipc_demo.rs"

[[bin]]
name = "ipc_demo_new"
path = "src/ipc_demo_new.rs"

[[bin]]
name = "ipc_test"
path = "src/ipc_test.rs"

[[bin]]
name = "grid_client_demo"
path = "src/grid_client_demo.rs"

[[bin]]
name = "ipc_server_demo"
path = "src/ipc_server_demo.rs"

[[bin]]
name = "ipc_server_demo_new"
path = "src/ipc_server_demo_new.rs"

[[bin]]
name = "grid_layout_client_demo"
path = "src/grid_layout_client_demo.rs"

[[bin]]
name = "test_new_features"
path = "src/test_new_features.rs"

[[bin]]
name = "test_dynamic_grid"
path = "src/test_dynamic_grid.rs"

[[bin]]
name = "test_dynamic_transitions"
path = "src/test_dynamic_transitions.rs"

[[bin]]
name = "test_dynamic_transitions_fixed"
path = "src/test_dynamic_transitions_fixed.rs"

[[bin]]
name = "test_animated_transitions"
path = "src/test_animated_transitions.rs"

[[bin]]
name = "test_comprehensive_window_management"
path = "src/test_comprehensive_window_management.rs"

[[bin]]
name = "test_event_driven_demo"
path = "src/test_event_driven_demo.rs"

[[bin]]
name = "test_bounds_demo"
path = "src/test_bounds_demo.rs"

# Focus tracking examples
[[example]]
name = "simple_focus_demo"
path = "examples/simple_focus_demo.rs"

[[example]]
name = "focus_tracking_demo"
path = "examples/focus_tracking_demo.rs"

[[example]]
name = "focus_music_demo"
path = "examples/focus_music_demo.rs"

[[example]]
name = "robust_grid_client"
path = "examples/robust_grid_client.rs"

[[example]]
name = "comprehensive_focus_demo"
path = "examples/comprehensive_focus_demo.rs"

[[example]]
name = "focus_demo_server"
path = "examples/focus_demo_server.rs"

[[bin]]
name = "realtime_monitor_grid"
path = "realtime_monitor_grid.rs"

[[bin]]
name = "debug_monitor_coords"
path = "src/debug_monitor_coords.rs"

[[bin]]
name = "simple_monitor_test"
path = "src/simple_monitor_test.rs"
