[package]
name = "e_grid"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "processthreadsapi", "shellapi", "consoleapi", "errhandlingapi"] }
crossterm = "0.27"
iceoryx2 = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"

[[bin]]
name = "grid_tracker"
path = "src/main.rs"

[[bin]]
name = "simple_test"
path = "src/simple_test.rs"

[[bin]]
name = "simple_grid"
path = "src/simple_grid.rs"

[[bin]]
name = "basic_grid"
path = "src/basic_grid.rs"

[[bin]]
name = "monitor_test"
path = "src/monitor_test.rs"

[[bin]]
name = "simple_grid_new"
path = "src/simple_grid_new.rs"

[[bin]]
name = "basic_example"
path = "src/basic_example.rs"

[[bin]]
name = "debug_positions"
path = "src/debug_positions.rs"

[[bin]]
name = "ipc_demo"
path = "src/ipc_demo.rs"

[[bin]]
name = "ipc_demo_new"
path = "src/ipc_demo_new.rs"

[[bin]]
name = "ipc_test"
path = "src/ipc_test.rs"

[[bin]]
name = "grid_client_demo"
path = "src/grid_client_demo.rs"

[[bin]]
name = "ipc_server_demo"
path = "src/ipc_server_demo.rs"

[[bin]]
name = "ipc_server_demo_new"
path = "src/ipc_server_demo_new.rs"

[[bin]]
name = "grid_layout_client_demo"
path = "src/grid_layout_client_demo.rs"

[[bin]]
name = "test_new_features"
path = "src/test_new_features.rs"

[[bin]]
name = "test_dynamic_grid"
path = "src/test_dynamic_grid.rs"

[[bin]]
name = "test_dynamic_transitions"
path = "src/test_dynamic_transitions.rs"

[[bin]]
name = "test_dynamic_transitions_fixed"
path = "src/test_dynamic_transitions_fixed.rs"

[[bin]]
name = "test_animated_transitions"
path = "src/test_animated_transitions.rs"
