[package]
name = "e_grid"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "processthreadsapi", "shellapi", "consoleapi", "errhandlingapi"] }
crossterm = "0.27"

[[bin]]
name = "grid_tracker"
path = "src/main.rs"

[[bin]]
name = "simple_test"
path = "src/simple_test.rs"

[[bin]]
name = "simple_grid"
path = "src/simple_grid.rs"

[[bin]]
name = "basic_grid"
path = "src/basic_grid.rs"

[[bin]]
name = "monitor_test"
path = "src/monitor_test.rs"

[[bin]]
name = "simple_grid_new"
path = "src/simple_grid_new.rs"

[[bin]]
name = "basic_example"
path = "src/basic_example.rs"

[[bin]]
name = "debug_positions"
path = "src/debug_positions.rs"
