@echo off
echo Testing client grid display...
cd /d c:\w\demos\e_midi\e_grid

echo Starting e_grid server in background...
start /min cargo run --bin e_grid server

echo Waiting for server to start...
ping 127.0.0.1 -n 4 > nul

echo Running client test...
cargo run --bin test_client_grid_display
